= PPWCode .NET projects

An overview of the different .NET projects within PPWCode.

== Libraries

These are the core libraries used in PPWCode .NET solutions.

These libraries are all actively maintained.

`PPWCode.Vernacular.Contracts.I`::
- Helper library to write design-by-contract code.
- Support for .NET full framework and recent .NET SDKs.

`PPWCode.Vernacular.Exceptions.IV`::
- Library with base exception types.
- Support for .NET full framework and recent .NET SDKs.

`PPWCode.Vernacular.Exceptions.V`::
- Library with base exception types.
- Support for recent .NET SDKs.

`PPWCode.Vernacular.Semantics.IV`::
- Library with base classes and interfaces.
- Support for .NET full framework and recent .NET SDKs.

`PPWCode.Vernacular.Semantics.V`::
- Library with base classes and interfaces.
- Support for recent .NET SDKs.

`PPWCode.Vernacular.Persistence.IV`::
- Library with base classes and interfaces.
- Support for .NET full framework and recent .NET SDKs.

`PPWCode.Vernacular.Persistence.V`::
- Library with base classes and interfaces.
- Support for recent .NET SDKs.

`PPWCode.Vernacular.NHibernate.III`::
- Library with base classes and interfaces.
- Support for .NET full framework and recent .NET SDKs.

`PPWCode.Util.Authorization.I`::
- Library with helpers.
- Support for recent .NET SDKs.

`PPWCode.Util.Collection.I`::
- Library with helpers.
- Support for recent .NET SDKs.

`PPWCode.Util.DI.I`::
- Library with helpers.
- Support for recent .NET SDKs.

`PPWCode.Util.Time.I`::
- Library with helpers.
- Support for recent .NET SDKs.

`PPWCode.Util.Validation.III`::
- Library with base classes and interfaces.
- Support for .NET full framework and recent .NET SDKs.

== Hosts

These libraries are used as the base for the projects within PPWCode .NET solutions.  The solutions are often initially created using a template.  By moving code out of the template and into a library, we create a simpler upgrade path: it is easier to upgrade referenced libraries than it is to adapt an existing solution to a new template.

These libraries are all actively maintained.

`PPWCode.API.Core`::
- Library with base classes and interfaces for the `API` part of a solution.
- Support for recent .NET SDKs.

`PPWCode.Server.Core`::
- Library with base classes and interfaces for the `Server` part of a solution.
- Support for recent .NET SDKs.

`PPWCode.Server.Core.Hangfire`::
- Library with base classes and interfaces for a `Hangfire` specific `Server` part of a solution.
- Support for recent .NET SDKs.

`PPWCode.Server.Core.NServiceBus`::
- Library with base classes and interfaces for an `NServiceBus` specific `Server` part of a solution.
- Support for recent .NET SDKs.

`PPWCode.Host.Core`::
- Library with base classes and interfaces for the `Host` part of a solution.
- Support for recent .NET SDKs.

`PPWCode.Host.Core.Hangfire`::
- Library with base classes and interfaces for a `Hangfire` specific `Host` part of a solution.
- Support for recent .NET SDKs.

`PPWCode.Host.Core.WebApi`::
- Library with base classes and interfaces for a `WebApi` specific `Host` part of a solution.
- Support for recent .NET SDKs.

// == Legacy
//
// These libraries are older generations of PPWCode .NET libraries.  They are no longer _actively_ maintained, but we do update them upon request.
